---
- name: create MSSQL DBs
  win_dsc:
    resource_name: SqlDatabase
    Ensure: Present
    Name: "{{ item }}"
    ServerName: .
    InstanceName: "{{ outer_item.instance_name }}"
  with_items: 
    - "{{ outer_item.databases }}"
  when: outer_item.databases is defined