---
svcaccount: "{{ inventory_hostname_short }}\\{{ ansible_user }}"
rl_mssql_temp_folder: C:\Temp
rl_mssql_install_ssms: true
rl_mssql_iso_source:
  - name: SQLServer2019-x64-ENU-Dev.iso
    repo: http://192.168.1.241:8080/files
    #productkey: 
    
rl_mssql_ssms_source: 
  - name: SSMS-Setup-ENU.exe
    repo: http://192.168.1.241:8080/files
    product_id: 4A144470-B2E3-4614-8AAC-370A0C80C919
    arguments: /install /passive /norestart

rl_mssql_instances:
  - instance_name: MSSQLSERVER
    features: SQLENGINE
    instance_collation: SQL_Latin1_General_CP1_CI_AS
    sysadmins: 
      - sql.sysadmin
    sqlusers: 
      - sql.user
    setupadmins: 
      - sql.dbadmin
    svcaccount: svc.mssql
    svcpassword: Passw0rd.123
    instance_dir: C:\Program Files\Microsoft SQL Server
    installdb_path: C:\Program Files\Microsoft SQL Server\MSSQLSERVER\MSSQL\Data
    userldb_path: C:\Program Files\Microsoft SQL Server\MSSQLSERVER\MSSQL\Data
    userdblog_path: C:\Program Files\Microsoft SQL Server\MSSQLSERVER\MSSQL\Data
    tempdb_path: C:\Program Files\Microsoft SQL Server\MSSQLSERVER\MSSQL\Data
    tempdblog_path: C:\Program Files\Microsoft SQL Server\MSSQLSERVER\MSSQL\Data
    backup_path: C:\Program Files\Microsoft SQL Server\MSSQLSERVER\MSSQL\Backup
    databases: 
      - rl_mssql_db